version = 0.1
[default.deploy.parameters]
stack_name = "load-sample"
resolve_s3 = true
s3_prefix = "load-sample"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AppName=\"ddb-api\" StageName=\"prod\""
image_repositories = []
